package main

import "github.com/bwmarrin/discordgo"

var ChatLog = []*discordgo.Message{
	&discordgo.Message{
		ID:              "658165252050911233",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "dont @ me",
		Timestamp:       "2019-12-22T04:33:44.208000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658165232937599017",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "dnf is shit",
		Timestamp:       "2019-12-22T04:33:39.651000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658165210766508032",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "I regret using Fedora",
		Timestamp:       "2019-12-22T04:33:34.365000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658160834962259999",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "Zzzzzzzzzzzzzzzzzzzzzzz",
		Timestamp:       "2019-12-22T04:16:11.092000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658160826301284353",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "updates",
		Timestamp:       "2019-12-22T04:16:09.027000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658160820936769537",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "downloading",
		Timestamp:       "2019-12-22T04:16:07.748000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658160805010735114",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "still",
		Timestamp:       "2019-12-22T04:16:03.951000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658159435126145024",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "reeee",
		Timestamp:       "2019-12-22T04:10:37.345000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658159428453007382",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "why does dnf take forever",
		Timestamp:       "2019-12-22T04:10:35.754000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
	&discordgo.Message{
		ID:              "658159393879359508",
		ChannelID:       "361910177961738244",
		GuildID:         "",
		Content:         "bro",
		Timestamp:       "2019-12-22T04:10:27.511000+00:00",
		EditedTimestamp: "",
		MentionRoles:    []string{},
		Tts:             false,
		MentionEveryone: false,
		Author: &discordgo.User{
			ID:            "227567234921398273",
			Email:         "",
			Username:      "Renzix",
			Avatar:        "bdd3afd5f4eda5a8c85feffd413d8267",
			Locale:        "",
			Discriminator: "7867",
			Token:         "",
			Verified:      false,
			MFAEnabled:    false,
			Bot:           false,
		},
		Attachments:      []*discordgo.MessageAttachment{},
		Embeds:           []*discordgo.MessageEmbed{},
		Mentions:         []*discordgo.User{},
		Reactions:        []*discordgo.MessageReactions{},
		Pinned:           false,
		Type:             0,
		WebhookID:        "",
		Member:           (*discordgo.Member)(nil),
		MentionChannels:  []*discordgo.Channel{},
		Activity:         (*discordgo.MessageActivity)(nil),
		Application:      (*discordgo.MessageApplication)(nil),
		MessageReference: (*discordgo.MessageReference)(nil),
		Flags:            0,
	},
}
