
package main

import "github.com/bwmarrin/discordgo"


var ChatLog = []*discordgo.Message{
  &discordgo.Message{
    ID:              "658399642144473108",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "no I have nitro until 2021",
    Timestamp:       "2019-12-22T20:05:07.161000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399597722468383",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "omg do I not have nitro",
    Timestamp:       "2019-12-22T20:04:56.570000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399554973990923",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "oh i dont idk",
    Timestamp:       "2019-12-22T20:04:46.378000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "434196606464557064",
      Email:         "",
      Username:      "daveyjones01",
      Avatar:        "faa6d1016dae200bb615bf1467250c43",
      Locale:        "",
      Discriminator: "5397",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399538666799127",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "perfect",
    Timestamp:       "2019-12-22T20:04:42.490000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "434196606464557064",
      Email:         "",
      Username:      "daveyjones01",
      Avatar:        "faa6d1016dae200bb615bf1467250c43",
      Locale:        "",
      Discriminator: "5397",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399536393486346",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "but i have nitro",
    Timestamp:       "2019-12-22T20:04:41.948000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399510355116032",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "let's make a terminal the works over imap",
    Timestamp:       "2019-12-22T20:04:35.740000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399490541092864",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "no nitro <:pensivecowboy:606930372332093441>",
    Timestamp:       "2019-12-22T20:04:31.016000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "434196606464557064",
      Email:         "",
      Username:      "daveyjones01",
      Avatar:        "faa6d1016dae200bb615bf1467250c43",
      Locale:        "",
      Discriminator: "5397",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399155219070998",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "for this server",
    Timestamp:       "2019-12-22T20:03:11.069000+00:00",
    EditedTimestamp: "2019-12-22T20:03:14.054000+00:00",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658399143495991306",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "why are there a bunch of greyed-out emoji",
    Timestamp:       "2019-12-22T20:03:08.274000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "171804038113787905",
      Email:         "",
      Username:      "atlas",
      Avatar:        "6b8b045801ff5d8b1a234c8a0a01109c",
      Locale:        "",
      Discriminator: "8492",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
  &discordgo.Message{
    ID:              "658398874301366292",
    ChannelID:       "361910177961738244",
    GuildID:         "",
    Content:         "we are all tony",
    Timestamp:       "2019-12-22T20:02:04.093000+00:00",
    EditedTimestamp: "",
    MentionRoles:    []string{},
    Tts:             false,
    MentionEveryone: false,
    Author:          &discordgo.User{
      ID:            "434196606464557064",
      Email:         "",
      Username:      "daveyjones01",
      Avatar:        "faa6d1016dae200bb615bf1467250c43",
      Locale:        "",
      Discriminator: "5397",
      Token:         "",
      Verified:      false,
      MFAEnabled:    false,
      Bot:           false,
    },
    Attachments:      []*discordgo.MessageAttachment{},
    Embeds:           []*discordgo.MessageEmbed{},
    Mentions:         []*discordgo.User{},
    Reactions:        []*discordgo.MessageReactions{},
    Pinned:           false,
    Type:             0,
    WebhookID:        "",
    Member:           (*discordgo.Member)(nil),
    MentionChannels:  []*discordgo.Channel{},
    Activity:         (*discordgo.MessageActivity)(nil),
    Application:      (*discordgo.MessageApplication)(nil),
    MessageReference: (*discordgo.MessageReference)(nil),
    Flags:            0,
  },
}
